### ISSUE TITLE
Compatibility with HTML webpack plugin 4 alpha

### ISSUE THREAD

**Issue by knyy** [jantimon/favicons-webpack-plugin#140]
Good day!

As referenced from this issue: https://github.com/jantimon/html-webpack-plugin/issues/968#issuecomment-419022696 

FaviconsWebpackPlugin is not compatible with the  HTML Webpack Plugin 4 alpha, are there any alternatives you would recommend?

Thank you for your time.

**Comment by brunocodutra** [comment]
[webapp-webpack-plugin](https://github.com/brunocodutra/webapp-webpack-plugin) recently added support to html-webpack-plugin v4.

**Comment by brunocodutra** [comment]
I've proposed that before, however meerging them both together isn't trivial at all, as I ended up rewriting the whole thing almost from scratch over time, introducing lots of breaking changes along the way, and I don't have the bandwidth to work that out right now. If you, or anyone else, is interested in undertaking the effort I'll give all the support necessary.

**Comment by sibelius** [comment]
is this PR enough https://github.com/jantimon/favicons-webpack-plugin/pull/145?

**Comment by loyko-vitaliy** [comment]
I updated version lodash to fix some vulnerabilitie, but not all.
Current version of plugin  works with favicons package v^4.8.3 which have 3 vulnerabilitie in production. I think this fixed in new version favicons v5.3.0, but favicons-webpack-plugin crashed with it.So i decided to try webapp-webpack-plugin...

**Comment by jantimon** [comment]
Will be part of 3.x see #184
