### ISSUE TITLE
the plugin inflates the webapp by over 7mb worth of favicons

### ISSUE THREAD

**Issue by blurymind** [jantimon/favicons-webpack-plugin#171]
Is there a way to not do that? Without plugin: 2.6mb
With plugin: 9.7 mb in dist

This is unacceptable

**Comment by oller** [comment]
The client will only download the images it wants from all the possible images defined by this plugin, it's incorrect to assume that every client is going to download an additional 7mb.  That is not the case.

If you feel that strongly, suggest you take this up with all the browser developers (Google/Mozilla/Microsoft) and their lack of a standard, rather than erroneously at the authors of this plugin.

**Comment by blurymind** [comment]
my use case includes it being a progressive web app

**Comment by rickysullivan** [comment]
You could always run https://www.npmjs.com/package/imagemin-webpack-plugin on the output. And looks at what icons you don't need for a PWA.

**Comment by blurymind** [comment]
it would be nice if this  plugin compressed the images. There is just something strange about a bunch of favicons being several times bigger than the entire web page they serve

**Comment by jantimon** [comment]
@blurymind good idea but maybe it would rather be an enhancement for https://github.com/itgalaxy/favicons as this is the underlying library which does the generation
