### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by irenexixi** [jantimon/favicons-webpack-plugin#79]
![image](https://cloud.githubusercontent.com/assets/7159225/26145087/c209558e-3b1d-11e7-9fed-f505ee4b9291.png)

**Comment by irenexixi** [comment]
anybody know what error this is ? what should I do ?

**Comment by TomIsion** [comment]
I meet the same question.

To see your wrong message, when npm install this package, it will downing **PhantomJS** first. When your computer save the file from *https://github.com/Medium/phantomjs/releases/download/v2.2.1/phantomjs-2.1.1-windows.zip*, it caused something wrong.

So you could download this file by your self. Then save the file to *C:\Users\qqli\...*. After this, `npm install --save-dev favicons-webpack-plugin` again may solve your question.

**Comment by TomIsion** [comment]
Here is the same question I have.

![7fd2df65-d3c3-4e88-a3b3-da93806082f5](https://cloud.githubusercontent.com/assets/17807471/26340010/85ce4d22-3fbe-11e7-96ea-22d33be89d14.png)

After I save the .zip by myself. I solved the question.

![e7b3397a-a37f-4600-a17f-b1a045fdef83](https://cloud.githubusercontent.com/assets/17807471/26340040/b1726b3e-3fbe-11e7-97b0-f2e0b5415ff7.png)

Maybe the question caused by ** PhantomJS**.

**Comment by irenexixi** [comment]
@TomIsion ok, I'll have a try, Thank you ~

**Comment by irenexixi** [comment]
@

**Comment by irenexixi** [comment]
@ I‘m run  npm install --save-dev favicons-webpack-plugin again，it was successful.  See below:
![image](https://cloud.githubusercontent.com/assets/7159225/26389215/5910440c-408b-11e7-8707-02524d2a1239.png)  I don't know why, it's ok.

**Comment by TomIsion** [comment]
👍
